/**
 * app/api/upload-video/route.ts
 * ─────────────────────────────────────────────────────────────
 * POST /api/upload-video
 *
 * Called by the client after the user has previewed the video and
 * clicked "Upload to YouTube". Uploads the video and patches the WP post.
 *
 * Returns plain JSON (no streaming — upload is a single operation).
 */

import { NextRequest, NextResponse } from "next/server";
import { uploadToYouTube, updatePostVideoUrl } from "@/lib/video";

export const maxDuration = 120;

export async function POST(req: NextRequest) {
  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 });
  }

  const { postId, title, videoBase64, mimeType } = body as {
    postId?: number;
    title?: string;
    videoBase64?: string;
    mimeType?: string;
  };

  if (!postId || typeof postId !== "number") {
    return NextResponse.json({ error: "postId is required." }, { status: 400 });
  }
  if (!title?.trim()) {
    return NextResponse.json({ error: "title is required." }, { status: 400 });
  }
  if (!videoBase64) {
    return NextResponse.json({ error: "videoBase64 is required." }, { status: 400 });
  }

  const missingVars = ["YOUTUBE_CLIENT_ID", "YOUTUBE_CLIENT_SECRET", "YOUTUBE_REFRESH_TOKEN"]
    .filter((k) => !process.env[k]);
  if (missingVars.length > 0) {
    return NextResponse.json(
      { error: `YouTube not configured. Missing: ${missingVars.join(", ")}` },
      { status: 503 }
    );
  }

  try {
    const videoBuffer = Buffer.from(videoBase64, "base64");
    console.log(`[upload-video] Uploading ${videoBuffer.length} bytes to YouTube…`);

    const description = `This video accompanies the article: "${title.trim()}"\n\nGenerated by Aston VIP.`;
    const youtubeUrl = await uploadToYouTube(videoBuffer, title.trim(), description);
    console.log(`[upload-video] YouTube URL: ${youtubeUrl}`);

    await updatePostVideoUrl(postId, youtubeUrl);
    console.log(`[upload-video] WP post ${postId} updated.`);

    return NextResponse.json({ youtubeUrl });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[upload-video] Failed: ${msg}`);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
