/**
 * app/api/generate-video/route.ts
 * ─────────────────────────────────────────────────────────────
 * POST /api/generate-video
 *
 * Runs independently of the main generate pipeline.
 * The client calls this after a blog post is successfully created.
 *
 * SSE event shapes:
 *   { type: "progress", message: string }
 *   { type: "done",     youtubeUrl: string }
 *   { type: "error",    message: string }
 */

import { NextRequest, NextResponse } from "next/server";
import {
  generateVideoPrompt,
  generateVeoVideo,
  uploadToYouTube,
  updatePostVideoUrl,
} from "@/lib/video";

export const maxDuration = 300;

export async function POST(req: NextRequest) {
  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 });
  }

  const { postId, title, keyword, language } = body as {
    postId?: number;
    title?: string;
    keyword?: string;
    language?: string;
  };

  if (!postId || typeof postId !== "number") {
    return NextResponse.json({ error: "postId (number) is required." }, { status: 400 });
  }
  if (!title?.trim()) {
    return NextResponse.json({ error: "title is required." }, { status: 400 });
  }

  const missingVars = [
    "YOUTUBE_CLIENT_ID",
    "YOUTUBE_CLIENT_SECRET",
    "YOUTUBE_REFRESH_TOKEN",
  ].filter((k) => !process.env[k]);

  if (missingVars.length > 0) {
    return NextResponse.json(
      { error: `YouTube not configured. Missing env vars: ${missingVars.join(", ")}. Run scripts/youtube-auth.mjs to set up.` },
      { status: 503 }
    );
  }

  const encoder = new TextEncoder();
  const stream  = new TransformStream<Uint8Array, Uint8Array>();
  const writer  = stream.writable.getWriter();

  const send = (event: Record<string, unknown>) =>
    writer.write(encoder.encode(`data: ${JSON.stringify(event)}\n\n`)).catch(() => {});

  (async () => {
    try {
      // ── Step 1: generate video prompt ────────────────────────
      await send({ type: "progress", message: "Writing video prompt…" });
      const prompt = await generateVideoPrompt(
        title.trim(),
        keyword?.trim() || title.trim(),
        language || undefined
      );
      console.log(`[generate-video] Prompt: ${prompt.slice(0, 120)}…`);

      // ── Step 2: generate video via Veo 2 ─────────────────────
      // Reserve 55s at the end for upload + WP patch (upload is chunked streaming
      // so it can be slow on large files). Polling deadline = 240s.
      const videoBuffer = await generateVeoVideo(
        prompt,
        (msg) => {
          console.log(`[generate-video] ${msg}`);
          send({ type: "progress", message: msg });
        },
        240_000
      );
      console.log(`[generate-video] Video ready (${videoBuffer.length} bytes)`);

      // ── Step 3: upload to YouTube ─────────────────────────────
      await send({ type: "progress", message: "Uploading to YouTube…" });
      const description = `This video accompanies the article: "${title.trim()}"\n\nGenerated by Aston VIP.`;
      const youtubeUrl = await uploadToYouTube(videoBuffer, title.trim(), description);
      console.log(`[generate-video] YouTube URL: ${youtubeUrl}`);

      // ── Step 4: patch WordPress post ─────────────────────────
      await send({ type: "progress", message: "Saving video URL to WordPress…" });
      await updatePostVideoUrl(postId, youtubeUrl);
      console.log(`[generate-video] WP post ${postId} updated with video.`);

      await send({ type: "done", youtubeUrl });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[generate-video] Failed: ${msg}`);
      await send({ type: "error", message: msg });
    }
  })().finally(() => writer.close().catch(() => {}));

  return new Response(stream.readable, {
    headers: {
      "Content-Type":  "text/event-stream",
      "Cache-Control": "no-cache",
    },
  });
}
